"use strict";
angular.module("apanelApp", ["ngRoute", "ngCookies", "angularUtils.directives.dirPagination", "toaster", "angularjs-dropdown-multiselect", "ejangular"])

    .controller("AdditionalElementCodeSettingsController", AdditionalElementCodeSettingsController)
    .controller('serviceMasterController', ServiceMasterController)
    .controller('companyServiceMasterController', companyServiceMasterController)
    .controller("chartOfAccountLevel1Controller", ChartOfAccountLevel1Controller)
    .controller("chartOfAccountLevel2Controller", ChartOfAccountLevel2Controller)
    .controller("chartOfAccountLevel3Controller", ChartOfAccountLevel3Controller)
    .controller("chartOfAccountLevel4Controller", ChartOfAccountLevel4Controller)
    .controller("chartOfAccountLevel5Controller", ChartOfAccountLevel5Controller)
    .controller("chartOfAccountLevel6Controller", ChartOfAccountLevel6Controller)
    .controller("companyFiscalYearController", CompanyFiscalYearController)
    .controller("MonthlyLeaveBalanceController", MonthlyLeaveBalanceController)

    .controller("companyTaxYearController", CompanyTaxYearController)
    .controller("countryTaxYearController", CountryTaxYearController)
    .controller("companyFiscalYearPeriodController", CompanyFiscalYearPeriodController)
    .controller("companyTaxYearPeriodController", CompanyTaxYearPeriodController)
    .controller("countryTaxYearPeriodController", CountryTaxYearPeriodController)
    .controller("fiscalYearController", FiscalYearController)
    .controller("fiscalYearCloseController", FiscalYearCloseController)
    .controller("paymentTermController", PaymentTermController)
    .controller("taxCodeController", TaxCodeController)
    .controller("taxCodeYearController", TaxCodeYearController)
    .controller("taxCategoryController", TaxCategoryController)
    .controller("taxCategoryGLController", TaxCategoryGLController)
    .controller("taxCategoryGLOutputController", TaxCategoryGLOutputController)
    .controller("taxCategoryRCMController", TaxCategoryRCMController)
    .controller("taxCategoryRCMOutputController", taxCategoryRCMOutputController)
    .controller("ReportCurrencyExchangeController", ReportCurrencyExchangeController)

    .controller("taxYearController", TaxYearController)
    .controller("fiscalYearPeriodController", FiscalYearPeriodController)
    .controller("taxYearPeriodController", TaxYearPeriodController)
    .controller("voucherTypeMatrixController", VoucherTypeMatrixController)
    .controller("voucherTypeConfigController", voucherTypeConfigController)
    .controller("coaController", COAController)
    .controller("alternativeCOAController", AlternativeCOAController)
    .controller("alternativeGLController", AlternativeGLController)
    .controller("accountGroupController", accountGroupController)
    .controller("accountTypeController", AccountTypeController)
    .controller("glItemController", GLItemController)
    .controller("glCompanyInfoController", GLCompanyInfoController)
    .controller("glMappingController", glMappingController)
    .controller("generalLedgerListReportController", generalLedgerListReportController)
    .controller("managementChartofAccountEXController", ManagementChartofAccountEXController)
    .controller("managementChartofAccountFAController", ManagementChartofAccountFAController)
    .controller("exchangeGainLossController", exchangeGainLossController)
    .controller("roundingGLController", roundingGLController)
    .controller("registerController", registerController)
    .controller("employeeTransactionTypeController", employeeTransactionTypeController)
    .controller("employeeTransactionTypeGLController", employeeTransactionTypeGLController)
    .controller("employeeExpensesBookingController", employeeExpensesBookingController)
    .controller("employeeInformationController", employeeInformationController)
    .controller("employeeReportInfoController", employeeReportInfoController)
    .controller("apanelLoginController", apanelLoginController)
    .controller("apanelLogoutController", apanelLogoutController)
    .controller("stateController", stateController)
    .controller("districtController", districtController)
    .controller("cityController", cityController)
    .controller("bankAccountTypeController", bankAccountTypeController)
    .controller("bankBranchController", bankBranchController)
    .controller("bankCategoryController", bankCategoryController)
    .controller("bankChargeTypeController", bankChargeTypeController)
    .controller("bankChargeTypeGLController", bankChargeTypeGLController)
    .controller("bankController", bankController)
    .controller("bankMasterController", bankMasterController)
    .controller("bankSubCategoryController", bankSubCategoryController)
    .controller("cashMasterController", cashMasterController)
    .controller("paymentDeductionGLController", paymentDeductionGLController)
    .controller("activityController", activityController)
    .controller("activityPositionMappingController", activityPositionMappingController)
    .controller("activityPhoneController", activityPhoneController)
    .controller("activityResponsiblePersonController", activityResponsiblePersonController)
    .controller("budgetController", budgetController)
    .controller("budgetCategoryController", budgetCategoryController)
    .controller("budgetSubCategoryController", budgetSubCategoryController)
    .controller("budgetClassController", budgetClassController)
    .controller("budgetGroupController", budgetGroupController)
    .controller("budgetMasterController", budgetMasterController)
    .controller("budgetMasterReportController", budgetMasterReportController)
    .controller("paymentDeductionController", paymentDeductionController)
    .controller("companyParallelCurrencyController", CompanyParallelCurrencyController)
    .controller("currencyTransactionController", CurrencyTransactionController)
    .controller("exchangeRateController", ExchangeRateController)
    .controller("approvalConfigurationController", approvalConfigurationController)
    .controller("employeeBaseController", employeeBaseController)
    .controller("employeeCategoryController", EmployeeCategoryController)
    .controller("employeeGroupController", EmployeeGroupController)
    .controller("employeeTypeController", EmployeeCategoryController)
    .controller("employeeBudgetCategoryController", EmployeeBudgetCategoryController)
    //.controller("employeeJobDescriptionController", employeeJobDescriptionController)
    .controller("employeeBudgetCategoryDepartmentController", EmployeeBudgetCategoryDepartmentController)
    .controller("employeeBudgetMasterController", employeeBudgetMasterController)
    .controller("employeeBudgetMasterActivityController", employeeBudgetMasterActivityController)
    .controller("employeeBudgetMasterActivityPhoneController", employeeBudgetMasterActivityPhoneController)
    .controller("jobDescriptionCategoryController", jobDescriptionCategoryController)
    .controller("jobDescriptionSubCategoryController", jobDescriptionSubCategoryController)
    .controller("jobDescriptionItemController", jobDescriptionItemController)
    .controller("jobDescriptionController", jobDescriptionController)
    .controller("recruitmentProcessController", recruitmentProcessController)
    .controller("recruitmentProcessSetController", RecruitmentProcessSetController)
    .controller("recruitmentGroupController", recruitmentGroupController)
    .controller("interviewRankingController", interviewRankingController)
    .controller("salutationController", salutationController)
    .controller("complianceDocumentCategoryController", ComplianceDocumentCategoryController)
    .controller("complianceDocumentProofTypeController", complianceDocumentProofTypeController)
    .controller("complianceDocumentSubCategoryController", ComplianceDocumentSubCategoryController)
    .controller("complianceDocumentController", ComplianceDocumentController)
    .controller("complianceDocumentSetController", ComplianceDocumentSetController)
    .controller("documentConfigurationDesignationGroupController", DocumentConfigurationDesignationGroupController)
    .controller("complianceDocumentReportController", ComplianceDocumentReportController)
    .controller("salaryHeadGLController", salaryHeadGLController)
    .controller("directTaxPaymentHeadController", directTaxPaymentHeadController)
    .controller("sopDocumentController", SOPDocumentController)
    .controller("sopDocumentCategoryController", SOPDocumentCategoryController)
    .controller("sopDocumentSubCategoryController", SOPDocumentSubCategoryController)
    .controller("sopCategoryController", SOPCategoryController)
    .controller("sopSubCategoryController", SOPSubCategoryController)
    .controller("sopItemController", sopItemController)
    .controller("fixedAssetCategoryController", fixedAssetCategoryController)
    .controller("fixedAssetMasterController", fixedAssetMasterController)
    .controller("fixedAssetSubCategoryController", fixedAssetSubCategoryController)
    .controller("fixedAssetClassController", fixedAssetClassController)
    .controller("fixedAssetSubClassController", fixedAssetSubClassController)
    .controller("fixedAssetDepreciationRuleController", fixedAssetDepreciationRuleController)
    .controller("companyFixedAssetDepreciationRuleController", companyFixedAssetDepreciationRuleController)
    .controller("fixedAssetAttributeController", fixedAssetAttributeController)
    .controller("fixedAssetAttributeValueController", fixedAssetAttributeValueController)
    .controller("assetItemCharacteristicsController", assetItemCharacteristicsController)
    .controller("fixedAssetMasterGLController", fixedAssetMasterGLController)
    .controller("fixedAssetMasterBudgetTagController", fixedAssetMasterBudgetTagController)
    .controller("projectPlanningCategoryController", ProjectPlanningCategoryController)
    .controller("projectPlanningSubCategoryController", ProjectPlanningSubCategoryController)
    .controller("machineClassController", MachineClassController)
    .controller("assetItemController", AssetItemController)
    .controller("operationTypeController", OperationTypeController)
    .controller("operationCategoryController", OperationCategoryController)
    .controller("skillCategoryController", SkillCategoryController)
    .controller("operationActivityController", operationActivityController)
    .controller("characteristicsController", CharacteristicsController)
    .controller("characteristicsValueController", CharacteristicsValueController)
    .controller("materialCategoryController", materialCategoryController)
    .controller("materialSubCategoryController", materialSubCategoryController)
    .controller("materialGridController", MaterialGridController)
    .controller("materialTypeController", MaterialTypeController)
    .controller("materialGroup1Controller", MaterialGroup1Controller)
    .controller("materialGroup2Controller", MaterialGroup2Controller)
    .controller("materialGroup3Controller", MaterialGroup3Controller)
    .controller("materialGroup4Controller", MaterialGroup4Controller)
    .controller("materialAttributeController", MaterialAttributeController)
    .controller("materialAttributeValueController", MaterialAttributeValueController)
    .controller("materialGroupMasterController", MaterialGroupMasterController)
    .controller("materialGroupArticleController", materialGroupArticleController)
    .controller("materialGroupGLController", MaterialGroupGLController)
    .controller("materialMasterController", MaterialMasterController)
    .controller("materialMasterAlternativeUOMController", MaterialMasterAlternativeUOMController)
    .controller("materialAttributeMasterController", MaterialAttributeMasterController)
    .controller("materialMasterGLController", MaterialMasterGLController)
    .controller("materialStorageController", materialStorageController)
    .controller("fgcomponentController", FGComponentController)
    .controller("packingFormController", PackingFormController)
    .controller("seasonsController", SeasonsController)
    .controller("orderCategoryController", OrderCategoryController)
    .controller("orderControlStageController", OrderControlStageController)
    .controller("orderStatusController", OrderStatusController)
    .controller("dMMController", DMMController)
    .controller("criticalController", CriticalController)
    .controller("lineDayCriticalityController", LineDayCriticalityController)
    .controller("processCategoryController", ProcessCategoryController)
    .controller("processController", ProcessController)
    .controller("subProcessController", SubProcessController)
    .controller("subProcessCategoryController", SubProcessCategoryController)
    .controller("entityProcessTagController", EntityProcessTagController)
    .controller("processCriteriaController", ProcessCriteriaController)
    .controller("processSetController", ProcessSetController)
    .controller("subProcessSetController", SubProcessSetController)
    .controller("processTypeController", ProcessTypeController)
    .controller("companyProcessController", CompanyProcessController)
    .controller("companySubProcessController", CompanySubProcessController)
    .controller("recruitmentPlanningController", recruitmentPlanningController)
    .controller("processUoMController", processUoMController)
    .controller("productionProcessGroupController", ProductionProcessGroupController)
    .controller("itemCategoryController", ItemCategoryController)
    .controller("itemController", ItemController)
    .controller("itemSubCategoryController", ItemSubCategoryController)
    .controller("productCategoryController", ProductCategoryController)
    .controller("productSubCategoryController", ProductSubCategoryController)
    .controller("productGroupController", ProductGroupController)
    .controller("productController", ProductController)
    .controller("productionSettingsWithProcessUOMController", ProductionSettingsWithProcessUOMController)
    .controller("productionStatusController", ProductionStatusController)
    //.controller("recipeConfigController", RecipeConfigController)
    .controller("recipeConfigController", recipeConfigController)
    .controller("btnRMConsumptionController", btnRMConsumptionController)
    .controller("btnOutputController", btnOutputController)
    .controller("otherController", otherController)
    .controller("directorController", directorController)
    //.controller("partyController", PartyController)
    .controller("partyBaseController", partyBaseController)
    .controller("partyGroupController", PartyGroupController)
    .controller("partyGroupCategoryController", PartyGroupCategoryController)
    .controller("partyGroupSubCategoryController", PartyGroupSubCategoryController)
    .controller("partyGroupClassController", PartyGroupClassController)
    .controller("partyCategoryController", PartyCategoryController)
    .controller("partySubCategoryController", PartySubCategoryController)
    .controller("partyAccountGroupController", PartyAccountGroupController)
    .controller("partyAccountGroupGLController", partyAccountGroupGLController)
    .controller("partyReportController", partyReportController)
    .controller("partnerFunctionController", PartnerFunctionController)
    .controller("partnerDeterminationProcedureController", PartnerDeterminationProcedureController)
    .controller("pDPFunctionController", PDPFunctionController)
    .controller("interCompanyPartyController", InterCompanyPartyController)
    .controller("buyerCategoryController", BuyerCategoryController)
    .controller("intermediateItemEntityController", IntermediateItemEntityController)
    .controller("intermediateItemController", IntermediateItemController)
    .controller("companyCoaController", CompanyCoaController)
    .controller("unitController", UnitController)
    .controller("sectionController", SectionController)
    .controller("subSectionController", SubSectionController)
    .controller("subsectionStructureController", SubsectionStructureController)
    .controller("departmentController", DepartmentController)
    .controller("lineController", LineController)
    .controller("companyLineController", CompanyLineController)
    .controller("purchaseOrganisationController", PurchaseOrganisationController)
    .controller("purchaseGroupController", PurchaseGroupController)
    .controller("salesOrganisationController", SalesOrganisationController)
    .controller("salesGroupController", SalesGroupController)
    .controller("companySectionController", CompanySectionController)
    .controller("companySubSectionController", CompanySubSectionController)
    .controller("divisionController", DivisionController)
    .controller("companyDivisionController", CompanyDivisionController)
    .controller("companyDepartmentController", CompanyDepartmentController)
    .controller("subDivisionController", SubDivisionController)
    .controller("companySubDivisionController", CompanySubDivisionController)
    .controller("updatePlantController", UpdatePlantController)
    .controller("updateCompanyController", UpdateCompanyController)
    .controller("updateCompanyGroupController", UpdateCompanyGroupController)
    .controller("entityController", entityController)
    .controller("entityAllowanceController", entityAllowanceController)
    .controller("entityCostCenterController", entityCostCenterController)
    .controller("entityLineController", entityLineController)
    .controller("entityCalendarController", EntityCalendarController)
    //.controller("entityComponentCostingController", entityComponentCostingController)
    .controller("positionController", positionController)
    .controller("positionBudgetMasterController", positionBudgetMasterController)
    .controller("positionBudgetMasterActivityController", positionBudgetMasterActivityController)
    .controller("positionAllowanceController", positionAllowanceController)
    .controller("manpowerBudgetController", manpowerBudgetController)
    .controller("manpowerBudgetAllowanceController", manpowerBudgetAllowanceController)
    .controller("manpowerBudgetBudgetMasterController", manpowerBudgetBudgetMasterController)
    .controller("manpowerBudgetBudgetMasterActivityController", manpowerBudgetBudgetMasterActivityController)
    .controller("chartOfAccountRelationshipController", ChartOfAccountRelationshipController)
    .controller("designationController", DesignationController)
    .controller("designationGroupController", DesignationGroupController)
    .controller("designationMasterController", DesignationMasterController)
    .controller("legalDesignationController", LegalDesignationController)
    .controller("companyDesignationController", CompanyDesignationController)
    .controller("companyCostCenterController", companyCostCenterController)
    .controller("costCenterController", costCenterController)
    .controller("costCenterCategoryController", costCenterCategoryController)
    .controller("costCenterSubCategoryController", costCenterSubCategoryController)
    .controller("plantDesignationGroupSalaryRuleController", plantDesignationGroupSalaryRuleController)
    .controller('CreditLimitOpeningController', CreditLimitOpeningController)
    .controller("plantSalaryHeadSequenceController", PlantSalaryHeadSequenceController)
    .controller("brandController", BrandController)
    .controller("paymentModeController", PaymentModeController)
    .controller("unitOfMeasurementController", UnitOfMeasurementController)
    .controller("yearlyCalendarController", YearlyCalendarController)
    .controller("offDayMasterController", OffDayMasterController)
    .controller("holidayCalendarController", HolidayCalendarController)
    .controller("uOMConversionController", UOMConversionController)
    .controller("salesTypeController", SalesTypeController)
    .controller("hsnCodeController", HSNCodeController)
    .controller("countryHSNCodeController", CountryHSNCodeController)
    .controller("testingCategoryController", TestingCategoryController)
    .controller("hSNTaxPercentageControllerNew", HSNTaxPercentageControllerNew)
    .controller("mailReceiverController", mailReceiverController)
    .controller("mailReceiverServiceController", mailReceiverServiceController)
    .controller("administrativeMailReceiverServiceController", administrativeMailReceiverServiceController)
    .controller("mailLogController", mailLogController)
    .controller("salaryFixationController", salaryFixationController)
    .controller("salaryFixationSettingController", salaryFixationSettingController)
    .controller("shortLeavePolicyController", shortLeavePolicyController)
    .controller("workCenterCategoryController", WorkCenterCategoryController)
    .controller("workCenterSubCategoryController", WorkCenterSubCategoryController)
    .controller("workCenterBuyerTagController", WorkCenterBuyerTagController)
    .controller("legalSalaryGradeController", LegalSalaryGradeController)
    .controller("legalSalaryGradeDesignationController", LegalSalaryGradeDesignationController)
    .controller("legalSalaryStructureController", LegalSalaryStructureController)
    .controller("legalSalaryReportController", LegalSalaryReportController)
    .controller("manpowerBudgetDashboardController", manpowerBudgetDashboardController)
    .controller("annualNonCashController", annualNonCashController)
    .controller("workGroupController", WorkGroupController)
    .controller("credentialPolicyController", CredentialPolicyController)
    .controller("creditNoteTypeController", creditNoteTypeController)
    .controller("creditNoteTypeGLController", creditNoteTypeGLController)
    .controller("debitNoteTypeController", debitNoteTypeController)
    .controller("debitNoteTypeGLController", debitNoteTypeGLController)
    .controller("customerTranTypeController", customerTranTypeController)
    .controller("customerTranTypeGLController", customerTranTypeGLController)
    .controller("vendorTranTypeController", vendorTranTypeController)
    .controller("vendorTranTypeGLController", vendorTranTypeGLController)
    .controller("userController", UserController)
    .controller("employeeMobileAppsAuthorizationController", EmployeeMobileAppsAuthorizationController)
    .controller("userPasswordResetController", UserPasswordResetController)
    .controller("userAuthtokenController", UserAuthtokenController)
    .controller("userPasswordChangeController", UserPasswordChangeController)
    .controller("authTokenLockLogController", AuthTokenLockLogController)
    .controller("userLockLogController", UserLockLogController)
    .controller("authTokenLockController", AuthTokenLockController)
    .controller("userLockController", UserLockController)
    .controller("roleController", RoleController)
    .controller("roleDetailController", RoleDetailController)
    .controller("roleDetailActionController", RoleDetailActionController)
    .controller("userRoleController", UserRoleController)
    .controller("userAccessPlantController", userAccessPlantController)
    .controller("userRoleDetailController", UserRoleDetailController)
    .controller("userAccessAppController", UserAccessAppController)
    .controller("roleMappingPositionController", RoleMappingPositionController)
    .controller("roleMappingManPowerBudgetController", RoleMappingManPowerBudgetController)
    .controller("additionalRoleController", AdditionalRoleController)
    .controller("additionalRoleActionController", AdditionalRoleActionController)
    .controller("cPasswordChangeController", CPasswordChangeController)
    .controller("investmentTypeController", investmentTypeController)
    .controller("investmentTypeGLController", investmentTypeGLController)
    .controller("loanTypeController", loanTypeController)
    .controller("interTransactionTypeController", interTransactionTypeController)
    .controller("interTransactionTypeGLController", interTransactionTypeGLController)
    .controller("loanTypeGLController", loanTypeGLController)
    .controller("securityTypeController", securityTypeController)
    .controller("securityTypeGLController", securityTypeGLController)
    .controller("taxCodeGLController", TaxCodeGLController)
    .controller("payrollGroupController", PayrollGroupController)
    .controller("designationMasterConfigurationController", DesignationMasterConfigurationController)
    .controller("partyMappingController", partyMappingController)
    .controller("retentionAllowanceController", RetentionAllowanceController)
    .controller("misAccountDashboardController", misAccountDashboardController)
    .controller("serviceTypeController", serviceTypeController)
    .controller("serviceGroupController", serviceGroupController)
    .controller("serviceGroupGLController", ServiceGroupGLController)
    .controller("taxVariantController", TaxVariantController)
    .controller("employeeLocationController", EmployeeLocationController)
    .controller("buyerActivityController", buyerActivityController)
    .controller("organizationsBaseController", organizationsBaseController)
    .controller("localLanguageSalaryHeadController", localLanguageSalaryHeadController)
    .controller("departmentResponsiblePersonController", departmentResponsiblePersonController)
    .controller("shiftGroupController", shiftGroupController)
    .controller("plantSettingController", plantSettingController)
    .controller("shiftGroupDetailController", shiftGroupDetailController)
    .controller("tnaSettingMasterController", tnaSettingMasterController)
    .controller("userEntityController", userEntityController)
    .controller("processGroupController", processGroupController)
    .controller("machineVariantController", machineVariantController)
    .controller("maternityLeavePolicyNewController", maternityLeavePolicyNewController)
    .controller("attendanceGroupController", attendanceGroupController)
    .controller('specialTaxController', specialTaxController)
    .controller("sizeGroupController", sizeGroupController)
    .controller("attachmentController", attachmentController)
    .controller("gaugeFolderController", gaugeFolderController)
    .controller("operationConsumptionController", operationConsumptionController)
    .controller('employeeMobileAppsAuthorizationNewController', employeeMobileAppsAuthorizationNewController)
    .controller('disciplinaryActionCategoryController', disciplinaryActionCategoryController)
    .controller("entityConfigController", entityConfigController)
    .controller("planningTypesController", planningTypesController)
    .controller("planningTypesNewController", planningTypesNewController)
    .controller("productionBookingPeriodController", productionBookingPeriodController)
    .controller("issueCategoryController", issueCategoryController)
    .controller("issueSubCategoryController", issueSubCategoryController)
    .controller("issueImportanceController", issueImportanceController)
    .controller("subAssetTypeController", subAssetTypeController)
    .controller("SFGInventoryController", SFGInventoryController)
    .controller('SFGMovementController', SFGMovementController)
    .controller('EntitySFGInventoryController', EntitySFGInventoryController)
    .controller('employeeWorkTypeController', employeeWorkTypeController)
    .controller('machineCategoryController', machineCategoryController)
    .controller('machineSubCategoryController', machineSubCategoryController)
    .controller('costingItemController', costingItemController)
    .controller('CostingComponentController', CostingComponentController)
    .controller('CostingTypeComponentController', CostingTypeComponentController)
    .controller('OverHeadTypeController', OverHeadTypeController)
    .controller('OverHeadTypeGLSalesController', OverHeadTypeGLSalesController)
    .controller('OverHeadTypeGLParachasController', OverHeadTypeGLParachasController)
    .controller('ShiftRosterCreationController', ShiftRosterCreationController)
    .controller('discountTypeGLController', discountTypeGLController)
    .controller('guestUserController', guestUserController)
    .controller('documentTypeController', documentTypeController)
    .controller('qmsActivityCategoryController', qmsActivityCategoryController)
    .controller("qualityActivityCheckTypeController", qualityActivityCheckTypeController)
    .controller("qmsBusinessProcessController", qmsBusinessProcessController)
    .controller("qmsBusinessProcessTypeController", qmsBusinessProcessTypeController)
    .controller("CostingUpChargeController", CostingUpChargeController)
    .controller("DocumentSourceController", DocumentSourceController)
    .controller("DocumentLocationController", DocumentLocationController)
    .controller("DefectTypeController", DefectTypeController)
    .controller("RepairTypeController", RepairTypeController)
    .controller("DefectZoneController", DefectZoneController)
    .controller("QMSTestingMasterController", QMSTestingMasterController)
    .controller("InspectionMasterController", InspectionMasterController)
    .controller("ProcessParameterController", ProcessParameterController)
    .controller("DefectCheckLevelController", DefectCheckLevelController)
    .controller("costingTypesController", costingTypesController)
    .controller("InquiryTypeController", InquiryTypeController)
    .controller('leaveTypeController', leaveTypeController)
    .controller('notificationSettingController', notificationSettingController)
    .controller('EmployeeInfoController', EmployeeInfoController)
    .controller('InvoiceBudgetChargesSettingController', InvoiceBudgetChargesSettingController)
    .controller('complianceAttendanceSettingController', complianceAttendanceSettingController)
    .controller('GradeMasterController', GradeMasterController)
    .controller('InspectionTypeController', InspectionTypeController)
    .controller('QualityStatusController', QualityStatusController)
    .controller('StockKeepingUnitController', StockKeepingUnitController)
    .controller('GeneralAccountDeterminateController', GeneralAccountDeterminateController)
    .controller('materialSettingController', materialSettingController)
    .controller('MaterialMasterTypeController', MaterialMasterTypeController)
    .controller('RestTypeController', RestTypeController)
    .controller('OTLimitSettingController', OTLimitSettingController)
    .controller('OrderControlTypesController', OrderControlTypesController)

    .controller('otSlabController', otSlabController)
    .controller('OTUpdateConfigurationController', OTUpdateConfigurationController)
    .controller('PFPolicyController', PFPolicyController)
    .controller('OTPolicyController', OTPolicyController)
    .controller('gratuityPolicyController', gratuityPolicyController)

    .controller('salaryHeadController', salaryHeadController)
    .controller('BankCashPercentageSettingController', BankCashPercentageSettingController)
    .controller('AdditionalPayDayController', AdditionalPayDayController)
    .controller('EmployeeFixedServicMasterController', EmployeeFixedServicMasterController)
    .controller('SandWichLeaveOnHolidayController', SandWichLeaveOnHolidayController)

    .controller('EmployeeServiceTypeController', EmployeeServiceTypeController)
    .controller('bonusPolicyController', bonusPolicyController)
    .controller('BonusPolicyMonthlyRetainController', BonusPolicyMonthlyRetainController)
    .controller('salaryHeadWisePaymentModePolicyController', salaryHeadWisePaymentModePolicyController)

    .controller("fgzoneController", FGZoneController)
    .controller("fgcomponentController", FGComponentController)
    .controller("PlantWiseHRMSSettingController", PlantWiseHRMSSettingController)
    .controller('TaskAppliedOnController', TaskAppliedOnController)
    .controller('TaskDependentDatesController', TaskDependentDatesController)
    .controller('menuUserCodeController', menuUserCodeController)

    .controller('ESICPolicyController', ESICPolicyController)
    .controller('jobLocationController', jobLocationController)
    .controller('TaxPolicyController', TaxPolicyController)
    .controller('TaxPolicyHeaderController', TaxPolicyHeaderController)
    .controller("attendanceBonusPolicyController", attendanceBonusPolicyController)
    .controller('CurrencyRuleController', CurrencyRuleController)
    .controller('leaveTypeController', leaveTypeController)
    .controller('leavePolicyController', leavePolicyController)
    .controller('TaxTypeController', TaxTypeController)
    .controller('BOQCriteriaController', BOQCriteriaController)
    .controller("GratuityInsuranceAgreementController", GratuityInsuranceAgreementController)
    .controller("ProcessAndInventorySequenceController", ProcessAndInventorySequenceController)
    .controller("defectCodeController", DefectCodeController)
    .controller('hourlyLeaveReasonController', hourlyLeaveReasonController)
    .controller('ReportingGroupController', ReportingGroupController)
    .controller('FinalSettlementDeductionHeadController', FinalSettlementDeductionHeadController)
    .controller('ScanItemController', ScanItemController)
    .controller("MovementItemsController", MovementItemsController)
    .controller("MovementMaterialMasterController", MovementMaterialMasterController)
    .controller("NoticePeriodSettingController", NoticePeriodSettingController)
    .controller("LeaveYearDefinationController", LeaveYearDefinationController)
    .controller("AnnualLeaveProcessController", AnnualLeaveProcessController)
    .controller("TaxSavingGroupController", TaxSavingGroupController)
    .controller("TaxSavingItemController", TaxSavingItemController)
    .controller("TermsAndConditionsController", TermsAndConditionsController)
    .controller("EfficiencySlabController", EfficiencySlabController)
    .controller("MaterialMovementPurposeController", MaterialMovementPurposeController)
    .controller("ItemConsumptionController", ItemConsumptionController)
    .controller("AccountsGroupController", AccountsGroupController)
    .controller("ShrinkageGroupController", ShrinkageGroupController)
    .controller("FabricWidthController", FabricWidthController)
    .controller("ShadeController", ShadeController)
    .controller("baseMaterialAndArticleController", baseMaterialAndArticleController)
    .controller("DayStatusMasterController", DayStatusMasterController)
    .controller("AttendanceBonusMasterController", AttendanceBonusMasterController)
    .controller("WeeklyOffController", WeeklyOffController)
    .controller("OutPunchConfigurationController", OutPunchConfigurationController)
    .controller("RosterPatternController", RosterPatternController)
    .controller("AttendanceSourceConfigController", AttendanceSourceConfigController)
    .controller("TablesUploadController", TablesUploadController)
    .controller('EmployeeServiceBookingController', EmployeeServiceBookingController)
    .controller('EmployeeServicesRateController', EmployeeServicesRateController)
    .controller('OTFormulaController', OTFormulaController)
    .controller('ResidenceGroupController', ResidenceGroupController)
    .controller('TransportGroupController', TransportGroupController)
    .controller('CommercialAdditionalInfoController', CommercialAdditionalInfoController)
    .controller('PerformanceManagementMasterController', PerformanceManagementMasterController)
    .controller('PerformancePeriodController', PerformancePeriodController)
    .controller('VehicleMovementLocationsController', VehicleMovementLocationsController)
    .controller('ServicesApprovingAuthorityController', ServicesApprovingAuthorityController)
    .controller('ProductiveAllowanceRateSetupController', ProductiveAllowanceRateSetupController)
    .controller('PerformanceGroupController', PerformanceGroupController)
    .controller('IssueController', IssueController)
    .controller('IssueMasterController', IssueMasterController)
    .controller('PerformanceAttributeMasterController', PerformanceAttributeMasterController)
    .controller('PerformanceGradeMasterController', PerformanceGradeMasterController)
    .controller('BOQCostingApprovalSettingController', BOQCostingApprovalSettingController)
    .controller('GoalSettingApprovalController', GoalSettingApprovalController)
    .controller("DocumentCategoryController", DocumentCategoryController)
    .controller('ScatteredWeekOffController', ScatteredWeekOffController)
    .controller('TrainingMasterController', TrainingMasterController)

    .controller("StorageBinMasterController", StorageBinMasterController)
    .controller("OTRegionController", OTRegionController)
    .controller("QualityProcessController", QualityProcessController)
    .controller("PackingTypeController", PackingTypeController)
    .controller("ProductionBookingProcessparameterController", ProductionBookingProcessparameterController)
    .controller("UtilityGroupController", UtilityGroupController)


    .controller("ExperienceMasterController", ExperienceMasterController)
    .controller("EmployerMasterController", EmployerMasterController)
    .controller("QualificationMasterController", QualificationMasterController)
    .controller("UserAppAuthenticationController", UserAppAuthenticationController)
    .controller("AppRoleController", AppRoleController)
    .controller("UserAccessAppRoleController", UserAccessAppRoleController)
    .controller("WasteTypeController", WasteTypeController)
    .controller("UserEditControlController", UserEditControlController)
    .controller("QualitySetupController", QualitySetupController)
    .controller("DocumentSetupController", DocumentSetupController)
    .controller("ChartAccountSetupController", ChartAccountSetupController)
    .controller("ManagementChartAccountSetupController", ManagementChartAccountSetupController)
    .controller("DesignationSetupController", DesignationSetupController)
    .controller("AdditionalInfoController", AdditionalInfoController)
    .controller("ProductionOrderEntitySetupController", ProductionOrderEntitySetupController)
    .controller("MasterPlanSetUpController", MasterPlanSetUpController)
    .controller("RemarksControlController", RemarksControlController)
    .controller("TermsandConditionGroupController", TermsandConditionGroupController)
    .controller("DependantTaskController", DependantTaskController)
    .controller("SalesPurchaseTransactionTypeController", SalesPurchaseTransactionTypeController)
    .controller("CasteController", CasteController)
    .controller("voucherTypeAdditionalInfoController", voucherTypeAdditionalInfoController)

    


    .config(accountConfig)
    .config(AdministrationConfig)
    .config(CostingsConfig)
    .config(IEConfig)
    .config(addressConfig)
    .config(ProductionsConfig)
    .config(bankConfig)
    .config(CurrencyConfig)
    .config(employeeConfig)
    .config(fixedAssetConfig)
    .config(ProjectConfig)
    .config(LogsConfig)
    .config(MachineConfig)
    .config(MaterialConfig)
    .config(OrderManagementConfig)
    .config(OrganizationConfig)
    .config(PartyConfig)
    .config(ProcessConfig)
    .config(SecurityConfig)
    .config(SetupConfig)
    .config(WorkCenterConfig)
    .config(SkillConfig)
    .config(HumanResourceConfig)
    .config(PayrollsConfig)
    .config(IssueTrackerConfig)
    .config(ProductConfig)
    .config(ProductionsConfig)
    .config(TaskManagementConfig)
    .config(CommercialConfig)
    .config(AccessControllerConfig)
    .config(qmsConfig)
    .config(FarmingConfig)
    .config(leaveConfig)
    .config(EmployeeServicesConfig)
    .config(PayrollsConfig)
    .config(MeetingManagementConfig)
    .config(salesManagementConfig)
    .config(TaskSchedulerConfig)

    .config(["$routeProvider", "$locationProvider", "$httpProvider", "$compileProvider", function apanelConfig($routeProvider, $locationProvider, $httpProvider, $compileProvider) {
        $httpProvider.interceptors.push("errorInterceptor");
        $httpProvider.defaults.headers.common["X-Requested-With"] = "XMLHttpRequest";
        //$compileProvider.debugInfoEnabled(true);
        //$locationProvider.html5Mode({
        //    enabled: true,
        //    requireBase: false
        //});
        $routeProvider
            .when("/", {
                templateUrl: function (params) {
                    return "APanel/dashboard";
                }
            })
            .when("/dashboard", {
                templateUrl: function (params) {
                    return "APanel/dashboard";
                }
            })
            .when("/login", {
                templateUrl: "APanel/login",
                controller: "apanelLoginController"
            })
            .when("/logout", {
                template: " ",
                controller: "apanelLogoutController"
            })
            .when("/404/:msg", {
                templateUrl: function (params) {
                    return "error/httperror404?message=" + params.msg;
                }
            })
            .when("/405/:msg", {
                templateUrl: function (params) {
                    return "error/httperror405?message=" + params.msg;
                }
            })
            .otherwise({
                redirectTo: "/portal"
            });
    }])
    .run(["$rootScope", "$window", "$cookies", "$http", function ($rootScope, $window, $cookies, $http) {
        $rootScope.title = "Administration";
        $rootScope.bootPoint = "#!/";
        $window.companyGroupId = $cookies.get("groupId");
        $window.authenticationToken = $cookies.get("authToken");
        $window.employeeId = $cookies.get("employeeId");
        //  $rootScope.companyGroupLogo = virtualPath.LogoOrImage + $cookies.get("gImage");
        //$rootScope.userImage = virtualPath.EmployeeImage + $cookies.get("userImage");
        angular.isUndefinedOrNull = function (val) {
            return angular.isUndefined(val) || val === null || val === "";
        };
        $rootScope.report = function (file_src) {
            $("#iframe_div_for_report").empty();
            var frame = $('<iframe id="report">')
                .attr('height', '0px')
                .attr('visibility', 'hidden')
                .attr('width', '0px');
            frame.on('load', function () {

                try {
                    var text = angular.fromJson($('#report')[0].contentDocument.body.innerText);

                    if (text.hasOwnProperty('Message')) {
                        if (angular.isUndefinedOrNull(text.Message) === false) {
                            $('<div id="message">').attr('height', '0px')
                                .attr('visibility', 'hidden')
                                .attr('width', '0px').appendTo('#iframe_div_for_report');
                            $("#message").ejDialog({
                                title: "Error"
                            });
                            $("#message").ejDialog("setContent", text.Message);

                        }
                    }
                    else {
                        var text1 = $('#report')[0].contentDocument.body.innerText;

                        $('<div id="message">').attr('height', '0px')
                            .attr('visibility', 'hidden')
                            .attr('width', '0px').appendTo('#iframe_div_for_report');
                        $("#message").ejDialog({
                            title: "Error"
                        });
                        $("#message").ejDialog("setContent", text1);
                    }

                } catch (e) {


                }

            });


            frame.attr('src', file_src);
            frame.appendTo('#iframe_div_for_report');
        };


        $rootScope.MenuList = [
            { Href: "legal-salary-report", Description: "Legal Salary" },
            { Href: "compliance-Document-report", Description: "Compliance Document" },
            { Href: "gl-report", Description: "GL" }
        ];


    }])
    .filter("dateFilter", dateFilter)
    .filter("dateFiltering", dateFiltering)
    .filter("safecontent", safecontent)
    .directive("panelBody", panelBody)
    .directive("datepicker", datepicker)
    .directive("togglable", togglable)
    .directive("showErrors", showErrors)
    .directive("archiveRow", archiveRow)
    .directive("confirmModal", confirmModal)
    .directive("loader", loader)
    .directive("stringToNumber", stringToNumber)
    .directive("inputMaxLengthNumber", inputMaxLengthNumber)
    .directive("confirmCancel", confirmCancel)
    .directive("input", inputFocus)
    .directive("textarea", inputFocus)
    .directive("select", inputFocus)
    .directive("input", CodeChecker)
    .directive("ngEnter", ngEnter)
    .directive("nDecimals", nDecimals)
    .directive("onlyNumbers", onlyNumbers)
    .directive("confirmArchive", confirmArchive)
    .directive("confirmArchiveGeneric", confirmArchiveGeneric)
    .directive("tooltip", tooltip)
    .directive("modalTable", modalTable)
    .directive("dynamic", dynamic)
    .directive("capitalize", capitalize)
    .directive("ngFileSelect", ngFileSelect)
    .directive("compile", compile)
    .directive("manualValidation", manualValidation)
    .factory("errorInterceptor", errorInterceptor)
    .factory("baseService", baseService)
    .factory("cboService", cboService)
    .factory("factoryService", factoryService)
    .factory("fileReader", fileReader)
    .factory("dataShare", dataShare)
    .factory("addressService", addressService)
    .factory("bankService", bankService)
    .constant("commonMessage", commonMessage)
    .filter("sumByKey", sumByKey)
    ;