//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Library.Service.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ServiceResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ServiceResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Library.Service.Properties.ServiceResources", typeof(ServiceResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your don&apos;t have permission to access this company..
        /// </summary>
        public static string AccessDenyToCompany {
            get {
                return ResourceManager.GetString("AccessDenyToCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Machine Applicable cannot be {0}, as the data exists in {1}.
        /// </summary>
        public static string AlreadyExistAnotherTable {
            get {
                return ResourceManager.GetString("AlreadyExistAnotherTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This {0} used in {1} you cannot {2}.
        /// </summary>
        public static string AlreadyExistAnotherTableNotUpOrDel {
            get {
                return ResourceManager.GetString("AlreadyExistAnotherTableNotUpOrDel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application name not found!.
        /// </summary>
        public static string ApplicationNameNotFound {
            get {
                return ResourceManager.GetString("ApplicationNameNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default value already set for {0} !.
        /// </summary>
        public static string CharacteristicsValue {
            get {
                return ResourceManager.GetString("CharacteristicsValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is not define in web config file..
        /// </summary>
        public static string ControlAdminPassword {
            get {
                return ResourceManager.GetString("ControlAdminPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserId is not define in web config file..
        /// </summary>
        public static string ControlAdminUserId {
            get {
                return ResourceManager.GetString("ControlAdminUserId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not an employee..
        /// </summary>
        public static string EmployeeNotMap {
            get {
                return ResourceManager.GetString("EmployeeNotMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not responsible person for any entity in this company..
        /// </summary>
        public static string EmployeeNotMapWithEntity {
            get {
                return ResourceManager.GetString("EmployeeNotMapWithEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File path not found!.
        /// </summary>
        public static string FilePathNotFound {
            get {
                return ResourceManager.GetString("FilePathNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid group!.
        /// </summary>
        public static string GroupInvalid {
            get {
                return ResourceManager.GetString("GroupInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Formate is not valid. Please input png, jpg, jpeg, gif, doc, docx,xls, xlsx, xlx, ppt, pptx, pdf.
        /// </summary>
        public static string IsValidFileFormate {
            get {
                return ResourceManager.GetString("IsValidFileFormate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid username or password!.
        /// </summary>
        public static string LoginFailError {
            get {
                return ResourceManager.GetString("LoginFailError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default value already set for {0} !.
        /// </summary>
        public static string MaterialAttributeValue {
            get {
                return ResourceManager.GetString("MaterialAttributeValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple Credential Policy is not allow to insert in a company group..
        /// </summary>
        public static string MultipleCredentialPolicyInsertError {
            get {
                return ResourceManager.GetString("MultipleCredentialPolicyInsertError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password will expire within {0} days..
        /// </summary>
        public static string PasswordExpireAlert {
            get {
                return ResourceManager.GetString("PasswordExpireAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are system admin.You have all entity access..
        /// </summary>
        public static string PreRecruitmentSysAdmin {
            get {
                return ResourceManager.GetString("PreRecruitmentSysAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The record no longer exists..
        /// </summary>
        public static string RecordNoLonger {
            get {
                return ResourceManager.GetString("RecordNoLonger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some fields are required..
        /// </summary>
        public static string RequiredFieldMessage {
            get {
                return ResourceManager.GetString("RequiredFieldMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secured Client Configuration Error!.
        /// </summary>
        public static string SecuredClientInvalid {
            get {
                return ResourceManager.GetString("SecuredClientInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Authentication Token!.
        /// </summary>
        public static string TokenInvalid {
            get {
                return ResourceManager.GetString("TokenInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your authentication token is locked!.
        /// </summary>
        public static string TokenLocked {
            get {
                return ResourceManager.GetString("TokenLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update is not allowed after Posted..
        /// </summary>
        public static string UpdateNotAllowPosted {
            get {
                return ResourceManager.GetString("UpdateNotAllowPosted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update or Delete is not allowed..
        /// </summary>
        public static string UpdateOrDeleteNotAllow {
            get {
                return ResourceManager.GetString("UpdateOrDeleteNotAllow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your userId is locked!.
        /// </summary>
        public static string UserLocked {
            get {
                return ResourceManager.GetString("UserLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Virtual Directory name not found!.
        /// </summary>
        public static string VirtualDirectoryNameNotFound {
            get {
                return ResourceManager.GetString("VirtualDirectoryNameNotFound", resourceCulture);
            }
        }
    }
}
