//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aplos.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Aplos.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application name not found!.
        /// </summary>
        internal static string ApplicationNameNotFound {
            get {
                return ResourceManager.GetString("ApplicationNameNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This control admin user is not found in database. Please create new one..
        /// </summary>
        internal static string ControlAdminNotFound {
            get {
                return ResourceManager.GetString("ControlAdminNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please upload xls or xlsx file only..
        /// </summary>
        internal static string ExcelUploadError {
            get {
                return ResourceManager.GetString("ExcelUploadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occured. Id not found..
        /// </summary>
        internal static string IdNotFound {
            get {
                return ResourceManager.GetString("IdNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please upload jpg, png file only..
        /// </summary>
        internal static string ImageUploadError {
            get {
                return ResourceManager.GetString("ImageUploadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some fields are required..
        /// </summary>
        internal static string RequiredFieldMessage {
            get {
                return ResourceManager.GetString("RequiredFieldMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select Bank..
        /// </summary>
        internal static string SelectBank {
            get {
                return ResourceManager.GetString("SelectBank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select Cash..
        /// </summary>
        internal static string SelectCash {
            get {
                return ResourceManager.GetString("SelectCash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Virtual Directory name not found!.
        /// </summary>
        internal static string VirtualDirectoryNameNotFound {
            get {
                return ResourceManager.GetString("VirtualDirectoryNameNotFound", resourceCulture);
            }
        }
    }
}
