name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Show Workspace
      shell: powershell
      run: |
        Write-Host "Workspace: $env:GITHUB_WORKSPACE"
        Get-ChildItem $env:GITHUB_WORKSPACE -Recurse |
        Where-Object {
          $_.Name -like "*Library*" -or
          $_.Name -like "*Extension*"
        }

    - name: Restore NuGet
      shell: powershell
      run: |
        nuget restore APLOS.New.sln

    - name: Build Solution
      shell: powershell
      run: |
        msbuild APLOS.New.sln `
          /p:Configuration=Release `
          /p:Platform="Any CPU" `
          /m

    - name: Publish
      shell: powershell
      run: |
        msbuild APLOS\APLOS.csproj `
          /p:Configuration=Release `
          /p:DeployOnBuild=true `
          /p:WebPublishMethod=FileSystem `
          /p:PublishUrl=F:\Deploy\PratibhaPOP

    - name: Stop IIS
      shell: powershell
      run: |
        Import-Module WebAdministration

        if ((Get-WebAppPoolState -Name "pratibhapop").Value -eq "Started") {
          Stop-WebAppPool -Name "pratibhapop"
        }

    - name: Deploy Files
      shell: powershell
      run: |
        robocopy `
          "F:\Deploy\PratibhaPOP" `
          "F:\aPOP\Pratibha\IIS\pratibhaPOP" `
          /E /R:1 /W:1 /XF web.config

        if ($LASTEXITCODE -le 3) {
          exit 0
        } else {
          exit $LASTEXITCODE
        }

    - name: Start IIS
      shell: powershell
      run: |
        Import-Module WebAdministration

        if ((Get-WebAppPoolState -Name "pratibhapop").Value -ne "Started") {
          Start-WebAppPool -Name "pratibhapop"
        }
